apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapp
  namespace: test
  labels:
    app: kubeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeapp
  template:
    metadata:
      labels:
        app: kubeapp
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
